namespace PgmStudio.Vocabulary;

/// <summary>One word the studio uses, what it means, the other names a reader may meet it under, and the
/// words its definition leans on.</summary>
/// <param name="Term">The word, as every rule, screen and document spells it.</param>
/// <param name="Definition">What it means, in one or two short sentences.</param>
/// <param name="AlsoCalled">Other names a reader meets it under: an older word, a field's name, PGM's name.
/// Each names this term and no other.</param>
/// <param name="Related">The terms its definition leans on.</param>
public sealed record GlossaryTerm(string Term, string Definition, IReadOnlyList<string> AlsoCalled, IReadOnlyList<string> Related);

/// <summary>
/// <b>Every studio and mapmaking word the rules, the screens and the documents use, defined once.</b> A rule,
/// a finding or a tooltip uses these words and never explains one; <c>GET /api/glossary</c> serves this list for
/// a person or an agent to read before working with the studio.
/// </summary>
public static class Glossary
{
    /// <summary>Every term, by name.</summary>
    public static IReadOnlyList<GlossaryTerm> Terms { get; } =
    [
        new("3-D preview",
            "The studio's three-dimensional view of the world a plan or sketch builds, drawn before anything is exported.",
            ["iso view", "structure preview"], ["build", "canvas"]),
        new("action",
            "What a map.xml rule or a shop item does when it fires, such as giving a kit or sending a message.",
            [], ["apply rule", "shop"]),
        new("add",
            "A shape that builds ground; an override add is laid after every cut and replaces the column it lands on.",
            [], ["subtract", "shape", "layer"]),
        new("admin",
            "A person on the whitelist who may change any map, keep the members on the whitelist and delete library entries.",
            [], ["whitelist"]),
        new("apply rule",
            "A rule in a map.xml that attaches a filter to a region for an event, such as entering it or placing a block.",
            ["apply-rule"], ["region", "filter", "action", "void rule"]),
        new("approach",
            "The path of land leading from a team's side to a wool room.",
            [], ["lane", "wool room", "approach wall"]),
        new("approach wall",
            "A bedrock wall two blocks thick and three high, placed across an approach, that gives the defenders a line to hold.",
            ["bedrock wall", "defence wall"], ["approach", "shared edge"]),
        new("author",
            "A person a map is credited to; an author may edit the map, a contributor is credited but may not.",
            [], ["whitelist"]),
        new("band",
            "One layer of a band stack: a block or pattern and its thickness, in blocks or, on a slope stack, in degrees.",
            [], ["band stack", "pattern", "slope"]),
        new("band stack",
            "A pattern of bands laid one after another: down from the top, in from the edge, up from a height, or by slope.",
            [], ["band", "pattern", "slope"]),
        new("barrier",
            "A step three or more blocks high, which a player cannot cross without building up it.",
            [], ["step", "scramble", "face"]),
        new("basin",
            "A body of water or lava drawn as an outline that fills the low ground inside it to a stated level and digs nothing.",
            [], ["fluid", "pool", "fluid level"]),
        new("beam ends",
            "Log ends a building lays sticking out past each corner where two storeys meet, two per corner, showing their sawn faces.",
            [], ["storey", "timber frame"]),
        new("bend",
            "An edit that roughens chosen edges of a shape's outline into a natural coast without moving its corners.",
            [], ["wander", "coast", "point edit"]),
        new("bind",
            "To make one thing use a named library entry: inside the library by reference, in a map by a copy.",
            [], ["library entry", "house", "pattern", "palette"]),
        new("biome",
            "The Minecraft biome each block column carries, which colours its grass, leaves and water; the library keeps biome layouts to reuse.",
            [], ["column", "pattern"]),
        new("boulder",
            "A large rounded rock placed as decoration, standing on the ground like a stone a glacier carried and left.",
            ["rock", "erratic"], ["prop"]),
        new("box",
            "A rectangle the generator draws around one part of a layout, such as a hub or a wool approach.",
            [], ["layout", "hub", "approach"]),
        new("buffer",
            "A plan piece that makes no ground: it keeps an area empty on purpose, such as the hole inside a ring.",
            [], ["piece role", "hole"]),
        new("build",
            "To turn a sketch and its game settings into the Minecraft world a match is played in.",
            ["finish", "rasterize"], ["sketch", "export"]),
        new("build ceiling",
            "The highest level players may place blocks, twenty blocks above the average height of the map's ground.",
            ["build height"], ["float"]),
        new("build queue",
            "The line of requests waiting for a turn to build a world; the studio builds three at once and one per person.",
            [], ["build"]),
        new("build region",
            "An area over the void where players may place blocks.",
            ["build zone"], ["void", "crossing"]),
        new("built-in entry",
            "A library entry the studio ships with; every start restores it, so it cannot be edited or deleted.",
            [], ["library entry"]),
        new("canvas",
            "The drawing area of the Plan and Sketch tools, where the map is shown from above and edited.",
            [], ["3-D preview", "plan", "sketch"]),
        new("capture",
            "Placing a taken wool on its wool monument, which scores it; for a capture point, taking ownership of it.",
            [], ["wool", "wool monument", "capture point"]),
        new("capture pad",
            "The floor of a control point, built from blocks that take the colour of the team holding the point.",
            [], ["pad"]),
        new("capture point",
            "A place on the map a team owns by standing on it, which pays its owner score while held.",
            ["control point", "hill"], ["King of the Hill", "objective", "symmetry centre"]),
        new("Capture the Wool",
            "A game mode where each team takes the other team's wools from their wool rooms and places them on its own wool monuments.",
            ["CTW"], ["wool", "wool room", "wool monument"]),
        new("casing",
            "The block shell a core is built as, holding the lava that leaks out when players break through it.",
            [], ["core"]),
        new("cell",
            "One square of the plan grid; its size in blocks is set per plan, and the default is 4.",
            [], ["plan", "piece"]),
        new("change",
            "One numbered write to a map's plan, refinement, sketch or game settings, kept so the map can be compared and put back.",
            [], ["source", "refinement", "edit"]),
        new("channel",
            "A body of water or lava drawn as a line with a width and dug into the ground: a canal, a river or a moat.",
            [], ["fluid", "pool", "basin"]),
        new("check",
            "A test the studio runs on something an author made, reporting what it finds as problems, warnings or things left out.",
            ["gate", "lint"], ["finding"]),
        new("claim",
            "Ground already held by something placed earlier, so no prop may rest there: a road, a fluid, a prop, or a building plus one block.",
            [], ["prop", "kept clear", "road"]),
        new("coast",
            "Where a map's ground meets the void at its outer edge.",
            [], ["ground", "void"]),
        new("column",
            "Everything at one block position on the map, from the bottom of the world to the top; its highest standable surface is the ground there.",
            [], ["ground", "cell"]),
        new("compile",
            "To turn a plan into a sketch and game settings; pieces that touch at one height become one shape.",
            ["recompile"], ["plan", "sketch", "fuse", "build"]),
        new("compound region",
            "A region in a map.xml built from other regions, such as a union of them or everything outside one.",
            [], ["region"]),
        new("Configure",
            "The tool that sets up the game on a world: teams, spawns, protected areas and objectives.",
            [], ["game settings", "import"]),
        new("copied tree",
            "A tree cut block for block out of a world someone built it in, kept in the library with where and when it was cut.",
            [], ["prop", "library"]),
        new("core",
            "A Destroy the Core objective: an obsidian casing holding lava, won by breaking it until the lava leaks out below.",
            [], ["leak", "float", "destroy map", "objective"]),
        new("course",
            "One block-high layer of a wall, floor, roof or prop, counted from its own base: upward for walls and roofs, downward for floors.",
            [], ["storey", "plate", "team band"]),
        new("covered ground",
            "Ground with a roof drawn over it on the same layer of a sketch.",
            [], ["layer"]),
        new("crossing",
            "The whole way across the mid from one team's side to the other's: the build regions players bridge and the islands they cross.",
            [], ["build region", "mid", "front line", "team side"]),
        new("crown",
            "How much higher a push stands in its middle than at its outline; zero is flat, positive domes it, negative dishes it.",
            [], ["push", "skirt"]),
        new("cut record",
            "Where a copied tree was taken from: the world folder, the position of its foot there, and when it was cut.",
            [], ["copied tree", "recipe"]),
        new("deck",
            "The one course a storey stands on, laid across its interior; the ground storey's deck is the top of the plate.",
            [], ["storey", "plate"]),
        new("decoration",
            "What you add to the ground: trees, boulders, roads, water and buildings.",
            ["dressing"], ["prop"]),
        new("destroy map",
            "A map played for monuments or cores, where each team breaks the other's objective while defending its own.",
            ["DTM", "DTC", "Destroy the Monument", "Destroy the Core"], ["monument", "core", "mode ladder"]),
        new("document",
            "One stored description of a map at one level, or of a library entry, which a tool edits and the API reads and writes.",
            [], ["plan", "sketch", "game settings", "refinement", "map.xml"]),
        new("door approach",
            "The ground in front of a room's door wall kept free of decoration: twenty blocks out from a spawn room, ten from a wool room.",
            [], ["kept clear", "spawn room", "wool room", "approach"]),
        new("door head",
            "The blocks laid over a doorway, carrying the wall above the opening; square, or arched with stairs in its corners.",
            ["lintel"], ["course"]),
        new("edit",
            "One change at one place in a map's document: adding, setting, moving or removing a value, as a finding proposes or a change made.",
            [], ["finding", "change", "document"]),
        new("export",
            "The finished map the studio hands out: its map.xml, and for a map drawn in the studio the world and its picture, in one download.",
            [], ["map.xml", "map picture", "build"]),
        new("face",
            "Ground too steep to walk up: a step of three blocks or more, or a slope the palette paints as cliff.",
            ["cliff"], ["step", "barrier", "slope"]),
        new("feet",
            "The blocks of a prop's lowest course; the ground under them is what the prop rests on and what every placement check reads.",
            [], ["seat", "prop", "footing"]),
        new("filter",
            "A condition in a map.xml, such as a team or a material, that a rule tests before letting something happen.",
            [], ["region", "apply rule"]),
        new("finding",
            "One problem the studio reports about something an author made: the rule it breaks, a sentence with the measured numbers, and what it is about.",
            [], ["problem", "left out", "warning", "check"]),
        new("flight",
            "A shape that climbs at a steady slope, built as a run of one-block steps a player can walk up.",
            [], ["landing", "step", "shape"]),
        new("float",
            "How many blocks a monument or core is raised above the ground beneath it.",
            [], ["monument", "core", "build ceiling"]),
        new("floor",
            "The height inside its layer where a shape's ground starts; the shape's thickness is counted up from it.",
            [], ["shape", "layer", "span", "deck"]),
        new("fluid",
            "Water or lava placed as decoration, drawn as a channel, a pool or a basin and filled level to one height.",
            [], ["channel", "pool", "basin", "fluid level"]),
        new("fluid level",
            "The one height a body of water or lava fills to along its whole length; unless stated, the lowest ground it crosses.",
            [], ["fluid"]),
        new("footing",
            "A course ringing a building's plate one block out on every side; a house carries none.",
            [], ["plate", "feet"]),
        new("footprint",
            "The area a thing covers on the map, seen from above: a building or room inside its walls, a prop at its base.",
            [], ["room", "prop", "column"]),
        new("foundation",
            "The stone the studio lays under a spawn or wool room to level its floor at the highest ground of its footprint.",
            [], ["room", "plate", "footprint"]),
        new("front line",
            "The edge of a team's side that faces the enemy across a build region; players bridge from here into the mid.",
            ["frontline", "frontline face"], ["team side", "mid", "crossing"]),
        new("fuse",
            "Of plan pieces: to join into one sketch shape when compiled, because they touch and stand at the same height.",
            [], ["compile", "piece", "group"]),
        new("game settings",
            "What a map is played for and by whom: its teams, spawns, protections, build regions and objectives, set in Configure.",
            ["intent"], ["Configure", "objective"]),
        new("gap",
            "The distance across the void between two islands, which players bridge.",
            [], ["island", "build region", "mid"]),
        new("generator",
            "The tool that creates complete layouts from a few settings: players, symmetry and size.",
            ["composer"], ["layout", "box"]),
        new("ground",
            "The surface a player can stand and walk on: terrain the map drew, as against void, fluid, or anything built on top of it.",
            ["land", "terrain"], ["void", "column", "slope"]),
        new("group",
            "A set of shapes on one layer treated as one landmass: copied by the symmetry, terraformed and kept clear together.",
            [], ["shape", "layer", "symmetry", "terraform"]),
        new("group of buildings",
            "Buildings standing within a passage of each other, treated as one: the passage is owed round the group, not between its houses.",
            [], ["passage"]),
        new("half-turn",
            "A symmetry that turns the design 180 degrees for a second team; a quarter-turn turns it by 90 degrees three times for four teams.",
            [], ["symmetry", "symmetry copy"]),
        new("hole",
            "Void enclosed on every side by ground or build regions, so players have to go around it.",
            [], ["buffer", "island", "rotation"]),
        new("house",
            "A building from the library, made of wings, storeys and a roof, placed as decoration or over a spawn or wool room.",
            ["room style", "house style"], ["wing", "storey", "library"]),
        new("hub",
            "The central area of a team's side, which the spawn, the wool approaches and the front line connect to.",
            [], ["team side", "approach"]),
        new("import",
            "Bringing a Minecraft world built outside the studio into it, without a map.xml, so it can be configured into a map.",
            [], ["Configure", "map.xml"]),
        new("iron cube",
            "A cube of iron blocks beside a spawn room that grows back after it is mined, so the team always has iron.",
            [], ["spawn", "marker", "room piece"]),
        new("island",
            "Ground a player can walk all over without building; ground separated from it by void is a different island.",
            ["landmass", "component"], ["stepping stone", "gap", "shared edge"]),
        new("isolation cut",
            "A build region inside one team's own side that separates a piece from the rest, so its defenders must bridge back.",
            [], ["build region", "team side", "gap"]),
        new("junction",
            "A place where two or more lanes meet.",
            [], ["lane", "hub"]),
        new("kept clear",
            "Ground no decoration may take: spawns, wool rooms, structures, built ground, door approaches and shapes the sketch marks keep clear.",
            [], ["door approach", "objective clearance", "claim"]),
        new("King of the Hill",
            "A game mode won on score, where teams earn points for as long as they hold capture points.",
            ["KotH"], ["capture point"]),
        new("laid log",
            "A log turned on its side to lie along the wall or roof it is part of, so bark shows and the cut ends hide.",
            [], ["material", "course"]),
        new("landform",
            "What kind of ground an island is meant to be: plain, rolling, hills or mountain, judged by its height range for its size.",
            [], ["terraform", "island"]),
        new("landing",
            "A few cells of level ground at the end of a flight, in the direction it runs, that a player arrives on.",
            [], ["flight"]),
        new("lane",
            "A strip of ground players walk along between two places, such as from the hub to a wool room.",
            ["corridor", "wool lane"], ["approach", "junction", "hub"]),
        new("layer",
            "One slab of a sketch at its own height; a sketch stacks layers to build decks, galleries and floors over one another.",
            [], ["span", "shape", "group", "made thing"]),
        new("layout",
            "The general shape of a map seen without its looks: where the ground, the void, the build regions, the spawns and the objectives are.",
            ["board"], ["map", "plan"]),
        new("leak",
            "A core leaks when its lava flows a set distance below it, which is how the attackers win it.",
            [], ["core", "float"]),
        new("left out",
            "A finding that says the map was built but one thing the author made is not in it. The API calls it a decline.",
            ["decline"], ["finding", "problem", "warning", "prop"]),
        new("library",
            "Patterns, palettes, houses, trees, boulders and biomes to reuse in any map; each map keeps its own copy.",
            [], ["library entry", "recipe", "pattern", "palette", "house"]),
        new("library entry",
            "One thing kept in the library, such as a pattern, palette, house, tree or boulder.",
            ["library row"], ["library"]),
        new("made thing",
            "An object drawn out of sketch layers marked as made, such as a ship or statue; it is not ground and nothing rests on it.",
            [], ["layer", "seat", "structure"]),
        new("map",
            "The complete thing a match is played on: its layout, its terraformed and painted ground, its decoration and structures, and its game settings.",
            [], ["layout", "game settings"]),
        new("map picture",
            "The picture a PGM server lists a map by, drawn from the view the author marks or from above the map.",
            ["map.png"], ["export"]),
        new("map.xml",
            "The file beside a world that tells PGM a map's teams, spawns, regions, filters and objectives.",
            [], ["PGM", "region", "filter", "apply rule", "game settings"]),
        new("mark",
            "A terraform control that holds a patch of ground at a chosen height: a point, a line, an area, a scarp or a group's rim.",
            ["relief mark"], ["terraform", "push", "tread", "reach"]),
        new("marker",
            "A point placed on a plan piece saying where a spawn, wool, iron cube, monument or core is built.",
            ["placement"], ["piece", "iron cube"]),
        new("material",
            "What fills a palette part, a building course or a whole shape: one block or one pattern.",
            [], ["pattern", "palette part", "course", "shape"]),
        new("mid",
            "The open void between the teams' front lines, sometimes with islands in it; players build across it.",
            ["middle"], ["front line", "crossing"]),
        new("mode ladder",
            "Match times at which each objective that opts in turns into a softer block, so a destroy match can end.",
            [], ["monument", "core", "destroy map"]),
        new("monument",
            "A Destroy the Monument objective: a small block structure one team defends and the other wins by breaking. PGM calls it a destroyable.",
            ["destroyable"], ["core", "float", "mode ladder", "destroy map"]),
        new("monument form",
            "The shape a monument is built in: a pillar one block wide, a cube, or a plus-shaped column.",
            ["destroyable form", "destroyable style"], ["monument", "column"]),
        new("note",
            "A remark an admin pins to one place on a map, which an agent answers and the author closes.",
            [], ["admin", "token"]),
        new("objective",
            "What a match is played for: a wool to capture, a monument or core to break, or a capture point to hold.",
            ["goal"], ["wool", "monument", "core", "capture point"]),
        new("objective clearance",
            "The ground round an objective kept free of decoration: what its structure covers grown by four blocks, and ten blocks round its marker.",
            ["goal clearance"], ["kept clear", "objective"]),
        new("objective marker",
            "A small coloured cube or cross the studio hangs high over an objective, above the build ceiling, so players see where it is.",
            ["goal marker"], ["objective", "build ceiling"]),
        new("observer platform",
            "The bedrock platform above the map where observers start, with signs giving the map's name and authors.",
            [], ["spawn"]),
        new("pad",
            "The square of blocks, two or three wide, a spawn or wool point sits on; the point the map exports is its centre.",
            [], ["room", "spawn room", "wool room"]),
        new("paint",
            "To give the ground its blocks: the plain stone the ground is built in becomes what a palette or a material names.",
            [], ["palette", "material", "ground", "column"]),
        new("palette",
            "A set of patterns that gives ground its look: one each for its rim, surface, wall and fill.",
            ["theme"], ["pattern", "palette part"]),
        new("palette part",
            "One of the four parts of ground a palette gives a pattern: the rim, the surface, the wall and the fill.",
            ["bucket"], ["palette", "rim"]),
        new("passage",
            "The strip of open ground, eight blocks wide, a building or group of buildings must leave along every side.",
            [], ["group of buildings"]),
        new("pattern",
            "A saved mix of blocks, such as layers, patches, stripes, a checkerboard or a team colour, that fills part of a palette or a building.",
            ["style"], ["palette", "material", "band stack", "team colour"]),
        new("period",
            "The size in blocks of the features a pattern varies over across the ground; its rise is the same size measured upward.",
            [], ["pattern"]),
        new("PGM",
            "The Minecraft server plugin that loads a map's world and map.xml and runs its matches.",
            [], ["map.xml"]),
        new("piece",
            "A rectangle of ground in a plan, standing at one surface height, whose role says what it is for.",
            [], ["plan", "cell", "surface", "piece role"]),
        new("piece role",
            "What a plan piece is for: plain ground, a spawn, a wool room, or a buffer that keeps space empty.",
            [], ["piece", "room piece", "buffer"]),
        new("pitch",
            "How steeply a roof climbs: blocks of rise for each block in from the wall.",
            [], ["roof form"]),
        new("plan",
            "The coarsest description of a map: pieces on a grid of cells saying where the land, spawns and objectives go, and how high it stands.",
            [], ["piece", "cell", "marker", "compile", "sketch"]),
        new("plan version",
            "The number a plan states for the format it is written in; the studio reads only the current one.",
            [], ["plan"]),
        new("plate",
            "The floor slab a building stands on, laid downward from the course players walk on; its top course is the ground storey's floor.",
            [], ["deck", "footing", "storey"]),
        new("point",
            "One corner of a shape's outline.",
            ["vertex"], ["shape"]),
        new("point edit",
            "An edit to one point of a shape's outline: inserting a point, moving it, or removing it, leaving every other point where it was.",
            [], ["bend", "point", "refinement"]),
        new("pool",
            "A body of water or lava drawn as a closed outline, dug out and filled: a lake or a harbour.",
            [], ["fluid", "channel", "basin"]),
        new("problem",
            "A finding that stops the work: nothing is built, stored or exported until it is fixed. The API calls it a refusal.",
            ["refusal"], ["finding", "left out", "warning"]),
        new("prop",
            "One placed piece of decoration: a tree, boulder, building, road, body of water or lava, patch of flora, or chest.",
            [], ["decoration", "seat", "claim"]),
        new("protection",
            "An area of the map players may not enter or change, such as the area around a spawn.",
            [], ["spawn", "wool room"]),
        new("push",
            "A terraform control that raises or lowers the ground inside a drawn outline by an amount, easing back to the ground around over its skirt.",
            [], ["mark", "skirt", "crown", "terraform"]),
        new("reach",
            "How far a terraform group's marks carry before the ground falls back to its base height, in blocks; zero lets the marks decide everything.",
            [], ["mark", "tread"]),
        new("read-back",
            "A report the studio takes from a built world as numbers, text or a picture, such as a walk, a section or the slopes.",
            [], ["build"]),
        new("recipe",
            "What a placed tree, boulder or building is made of, saved once in the library and copied into the sketch under a key.",
            [], ["prop", "library entry", "house"]),
        new("redstone line",
            "A line of redstone dust the studio lays to mark a boundary: across a wool room's entrance, and around the edge of a build region.",
            [], ["wool room", "build region"]),
        new("refinement",
            "What a map's source states on top of its plan: coasts, terraform, palettes, extra layers, shapes and decoration, applied in a fixed order.",
            [], ["source", "plan", "point edit", "bend", "change"]),
        new("region",
            "A named area in a map.xml, such as a spawn or a build region, that rules attach behaviour to.",
            [], ["filter", "apply rule", "compound region", "build region"]),
        new("rim",
            "The palette part that caps the ground along its edges, where it drops away or meets the void.",
            [], ["palette part", "void", "face"]),
        new("road",
            "A path drawn as decoration and marked as a way through the map; props keep their distance, and buildings may end it, never cross it.",
            ["paving"], ["prop", "standoff", "claim"]),
        new("roof form",
            "The shape of a roof: flat, gable, hip, gambrel, saltbox or shed.",
            [], ["pitch", "wing"]),
        new("room",
            "The floor a spawn or a wool stands on, holding its pad, chests and wool monuments, with or without a shell built round it.",
            [], ["spawn room", "wool room", "pad", "shell"]),
        new("room piece",
            "A plan piece with the spawn or wool-room role, holding the room built on it and the protected area around that room.",
            ["spawn piece", "wool room piece"], ["piece role", "spawn", "wool room", "protection"]),
        new("rotation",
            "Players moving from one lane to another around a hole without going back through one choke point.",
            [], ["lane", "hole"]),
        new("route",
            "The way players walk between two places the map is played between, such as a spawn and a wool room.",
            [], ["walking distance", "waypoint"]),
        new("scramble",
            "A step two blocks high, climbed by placing one block and jumping onto it.",
            [], ["step", "barrier"]),
        new("seat",
            "To set a prop, building or layer down on the ground below it; a prop seats on the lowest column under its feet.",
            [], ["prop", "feet", "column"]),
        new("shape",
            "One drawn piece of a sketch layer, such as a rectangle, polygon or line, with a height, that adds ground or cuts it away.",
            [], ["layer", "group", "add", "subtract", "shape kind"]),
        new("shape kind",
            "What a shape is drawn as: a rectangle, a circle, a polygon, a freehand lasso, or a polyline (a line drawn with a width).",
            [], ["shape", "point"]),
        new("shared edge",
            "Where two pieces, or a piece and a build region, touch along a straight stretch of their sides; players walk across it.",
            ["interface", "seam", "border"], ["piece"]),
        new("shell",
            "The walls and roof built round a room; an unstyled room gets the studio's own: bedrock walls, a bedrock lid and a team band.",
            [], ["room", "team band", "course", "casing"]),
        new("shop",
            "A menu of items a player buys with what they carry, opened by right-clicking a shopkeeper standing on the map.",
            [], ["action"]),
        new("shoulder",
            "The part of a mark outside its tread, where its height grades toward the ground beside it; its width sets how steep that grade is.",
            [], ["tread", "mark"]),
        new("size band",
            "The player count a map is built for: nano 6–13 players a team, micro 14–21, milli 22–31, centi 32 and up.",
            [], ["lane"]),
        new("sketch",
            "The detailed description of a map's ground: every outline and height, its palettes, and what stands on it, drawn in the Sketch tool.",
            [], ["layer", "shape", "group", "plan", "palette", "decoration", "terraform"]),
        new("skirt",
            "The distance outside a push's outline over which its lift falls back to the ground around it.",
            ["falloff"], ["push", "crown"]),
        new("slope",
            "How steeply the ground leans at a column, in degrees from level; a ramp climbing one block per block is 45.",
            ["incline", "inclination"], ["face", "palette"]),
        new("slug",
            "A map's short name in the studio: the lowercase name in its address and in every request that names it.",
            [], ["map"]),
        new("soil",
            "Grass or dirt of any kind: the only ground a tree may stand in.",
            [], ["surfacing block", "ground"]),
        new("source",
            "Everything a whole map is built from, sent in one request: its plan or drawing, its refinement, and where it came from.",
            [], ["refinement", "plan", "change"]),
        new("span",
            "The run of solid blocks one layer holds in one column, from its floor to its top.",
            [], ["layer", "column", "floor"]),
        new("spawn",
            "The place a team enters the match and returns to after dying, built as a room that only its own team may enter.",
            ["spawn point"], ["room piece", "protection", "team side"]),
        new("spawn room",
            "The room a team's players spawn in, raised on its room piece; it holds one wool monument for every wool the team captures.",
            ["spawn building", "spawn cube"], ["room", "pad", "wool monument", "shell"]),
        new("stage",
            "How far a map has come: plan, sketch, configure or edit. It marks progress and locks nothing.",
            [], ["plan", "sketch", "Configure"]),
        new("standoff",
            "The open ground a prop keeps between itself and the nearest road: three blocks for a tree, two for a boulder, none for anything else.",
            [], ["road", "prop"]),
        new("step",
            "The height difference between two neighbouring columns: one block is walked, two is scrambled, three or more is a barrier.",
            [], ["scramble", "barrier", "face", "column"]),
        new("stepping stone",
            "A small island holding no spawn or wool, standing in a build region, that players bridge to on their way across.",
            [], ["island", "mid", "crossing"]),
        new("storey",
            "One floor of a building: the room a player stands in, at least three blocks clear; a building stacks its storeys from the ground up.",
            [], ["course", "deck", "wing"]),
        new("stroke",
            "A line drawn across the ground as decoration, which repaints the surface it crosses with a material and adds no height.",
            [], ["road", "prop", "decoration"]),
        new("structure",
            "Something the studio builds for the game itself: a spawn room, a wool room, an approach wall or an objective. Never painted or decorated over.",
            [], ["spawn room", "room", "prop", "kept clear"]),
        new("subtract",
            "A shape that cuts ground away: it empties the columns it covers on its own layer.",
            [], ["add", "shape", "void"]),
        new("surface",
            "The height in blocks a plan piece stands at; neighbouring pieces at different surfaces make steps, ramps and cliffs.",
            [], ["piece", "terraform", "palette"]),
        new("surfacing block",
            "A block that is only ever the top block of ground, one block thick: grass, podzol, mycelium or farmland.",
            [], ["soil", "band"]),
        new("symmetry",
            "How the part you design is copied for the other teams: rotated or mirrored.",
            [], ["symmetry copy", "symmetry centre", "half-turn"]),
        new("symmetry centre",
            "The point the symmetry turns or reflects the map about; for a mirror, the line through it is the mirror line.",
            [], ["symmetry", "symmetry copy", "capture point"]),
        new("symmetry copy",
            "One of the copies the symmetry makes of the part you design, one for each other team.",
            ["symmetry image", "orbit image"], ["symmetry"]),
        new("team band",
            "A course in a room's wall laid in the team's colour, or in the wool's colour in a wool room.",
            [], ["shell", "course"]),
        new("team colour",
            "The dye colour a team plays in; a team colour pattern lays clay, wool or glass in it on that team's ground.",
            ["team tint"], ["pattern", "team side", "island"]),
        new("team side",
            "The ground that belongs to one team: its spawn, its wool rooms and the land joining them, up to its front line.",
            ["team ground"], ["hub", "front line", "island"]),
        new("terraform",
            "Shaping the flat ground into hills, slopes and cliffs.",
            ["relief"], ["surface"]),
        new("timber frame",
            "A building's corner posts, beam ends and the laid log course they belong to; the three are one frame and one wood.",
            [], ["beam ends", "course"]),
        new("token",
            "A key a person issues in the studio so a script or agent can act as them, with at most a member's rights.",
            [], ["whitelist", "admin"]),
        new("tone family",
            "A group of blocks that read as one colour of ground from a distance, such as stone and andesite, or sand and sandstone.",
            [], ["pattern", "boulder"]),
        new("tread",
            "How much of a line mark's width is held flat either side of its line; past it the ground grades into its neighbour.",
            [], ["mark", "shoulder"]),
        new("verge",
            "The outermost ring of a roof, running down both sloped edges at a gable end; it may be a different block from the roof.",
            [], ["roof form"]),
        new("void",
            "Empty space with no ground under it, down to the bottom of the world; players cross it only by building.",
            [], ["ground", "build region"]),
        new("void rule",
            "The one rule in a map.xml that stops players placing or breaking blocks over the void outside every build region.",
            [], ["build region", "void", "apply rule"]),
        new("walking distance",
            "How far a player walks between two places over the ground, going around void, never the straight line through the air.",
            ["walk"], ["route", "waypoint"]),
        new("wander",
            "How far, in blocks, a bend may push each new point of an outline off its edge.",
            [], ["bend"]),
        new("warning",
            "A finding the author may ignore: the work went ahead and everything they made is in it. The API calls it a complaint.",
            ["complaint"], ["finding", "problem", "left out"]),
        new("water lane",
            "A build region closed at the start of the match that opens later, when water fills it.",
            [], ["build region"]),
        new("waypoint",
            "A place a match is played between: a spawn, a wool room, a wool monument, a monument, a core or a capture point.",
            [], ["route", "walking distance"]),
        new("whitelist",
            "The studio's list of people who may change things in it, each a member or an admin.",
            [], ["admin", "token", "author"]),
        new("window host",
            "The wall block a window may be cut into; windows are spread across each unbroken run of it.",
            [], ["course"]),
        new("wing",
            "One rectangle of a building's plan; a building is one or more touching wings, each with its own roof and storey count.",
            [], ["wing joint", "storey", "roof form"]),
        new("wing joint",
            "Where two wings of one building meet along a whole edge, so one wing's roof marches into or projects through the other's.",
            [], ["wing"]),
        new("wobble",
            "How far an outline stated by its shape bulges in and out of its ellipse, as a share of its radius, below 1.",
            [], ["refinement"]),
        new("wool",
            "A coloured wool block kept in a wool room, which another team takes and carries to its own wool monument to capture.",
            [], ["wool room", "wool monument", "capture", "Capture the Wool"]),
        new("wool monument",
            "Where a team places a wool it has taken, to capture it.",
            ["pedestal"], ["wool", "capture"]),
        new("wool room",
            "The room a wool is kept in, defended by the team that owns it.",
            ["wool cage"], ["wool", "room piece", "protection"]),
    ];

    /// <summary>The terms a word names: its own term, or the term it is another name for, matched without
    /// case. Empty for a word the glossary does not define.</summary>
    public static IReadOnlyList<GlossaryTerm> Find(string word) =>
    [
        .. Terms.Where(term => string.Equals(term.Term, word, StringComparison.OrdinalIgnoreCase)
                               || term.AlsoCalled.Contains(word, StringComparer.OrdinalIgnoreCase)),
    ];
}
