<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\PgmStudio.Domain\PgmStudio.Domain.csproj" />
    <ProjectReference Include="..\PgmStudio.Analysis\PgmStudio.Analysis.csproj" />
    <ProjectReference Include="..\PgmStudio.Minecraft\PgmStudio.Minecraft.csproj" />
    <ProjectReference Include="..\PgmStudio.Pgm\PgmStudio.Pgm.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
