#!/usr/bin/env bash
# Writes the size table in docs/project-structure.md §3 — files, lines and the internal shape of every
# project under src/.
#
# The table is a fact about the tree, so it is counted rather than typed: a hand-written census is wrong
# between every pair of commits, and every row of the last one had drifted before anyone noticed. Run this
# after anything that moves files between projects or folders, and commit what it writes.
#
# A folder's count is RECURSIVE — what the folder holds, which is what a reader means by it — and a folder
# holding another says so, because `Compose/ 42` and `Compose/ 28` are both true of the same folder and only
# one of them answers "how big is Compose".
#
# Usage: tools/census.sh [--check]
#   --check writes nothing and exits 1 if the table is out of date.
set -uo pipefail
cd "$(dirname "$0")/.."

DOC=docs/project-structure.md
BEGIN='<!-- census: generated by tools/census.sh -->'
END='<!-- /census -->'

# Every .cs a project holds, plus .razor for the client, which is where half of its source lives.
sources() {
    find "$1" -name '*.cs' -o -name '*.razor' \
        | grep -v '/obj/' | grep -v '/bin/' | sort
}

shape() {   # top-level folders by what each holds, largest first, then whatever sits at the root
    local project=$1 prefix="src/$1/" root=0 out=''
    while read -r count folder; do
        if [ "$folder" = "." ]; then root=$count; continue; fi
        local nested
        nested=$(find "src/$project/$folder" -mindepth 1 -maxdepth 1 -type d ! -name obj ! -name bin | wc -l)
        if [ "$nested" -gt 0 ]; then
            out+="\`$folder/\` $count (nested) · "
        else
            out+="\`$folder/\` $count · "
        fi
    done < <(sources "src/$project" | sed "s|$prefix||" | awk -F/ '{print (NF>1 ? $1 : ".")}' \
             | sort | uniq -c | sort -k1,1nr -k2,2)

    if [ -z "$out" ]; then printf 'flat'; return; fi
    [ "$root" -gt 0 ] && out+="$root at root · "
    printf '%s' "${out% · }"
}

thousands() { printf '%s' "$1" | sed -E ':a; s/([0-9])([0-9]{3})($|,)/\1,\2\3/; ta'; }

table() {
    printf '%s\n' "$BEGIN"
    printf '| Project | Files | Lines | Internal shape |\n|---|---|---|---|\n'
    for path in src/PgmStudio.*/; do
        local project=${path#src/PgmStudio.}
        project=${project%/}
        local files lines form
        files=$(sources "src/PgmStudio.$project" | wc -l)
        lines=$(sources "src/PgmStudio.$project" | xargs -r wc -l | tail -1 | awk '{print $1}')
        form=$(shape "PgmStudio.$project")
        [ -z "$form" ] && form='flat'
        printf '| `%s` | %s | %s | %s |\n' "$project" "$files" "$(thousands "$lines")" "$form"
    done
    printf '%s\n' "$END"
}

fresh=$(table)
current=$(awk "/^${BEGIN//\//\\/}\$/,/^${END//\//\\/}\$/" "$DOC")

if [ "${1:-}" = '--check' ]; then
    if [ "$fresh" = "$current" ]; then echo "census is current"; exit 0; fi
    echo "census in $DOC is out of date — run tools/census.sh" >&2
    diff <(printf '%s\n' "$current") <(printf '%s\n' "$fresh") >&2
    exit 1
fi

if [ -z "$current" ]; then
    echo "no census markers in $DOC — add $BEGIN and $END around the table" >&2
    exit 1
fi

python3 - "$DOC" "$BEGIN" "$END" <<PY
import sys
doc, begin, end = sys.argv[1], sys.argv[2], sys.argv[3]
text = open(doc, encoding='utf-8').read()
head, rest = text.split(begin, 1)
_, tail = rest.split(end, 1)
open(doc, 'w', encoding='utf-8').write(head + '''$fresh''' + tail)
PY
echo "census written to $DOC"
