#:project mapgen/PgmStudio.MapGen.csproj
// A file-based app turns reflection-based JSON off by default, and a theme's materials are a polymorphic
// tagged union serialized that way — without this every material comes back as "reflection is disabled".
#:property JsonSerializerIsReflectionEnabledByDefault=true
// library-map: the studio's catalogue map, written as a mapgen spec.
//
//   dotnet run tools/library-map.cs [out.json]
//   dotnet run --project tools/mapgen -- --stages tools/out/library-map.spec.json
//
// One plot per thing the studio can make: every terrain pattern, the inward axis, every house preset, and a
// tree of every species and wood scattered over them. It exists to be walked and to be looked at — a map whose
// only job is to show whether the vocabulary still renders — which is why the plots are chosen to be awkward
// (an octagon sits exactly on a wall frame's corner threshold, a cross has to turn both kinds of corner) and
// why the paint is not curated. These themes are automatic choices made to probe expressiveness, not an
// author's taste, and they are deliberately not seeded into the library as if they were suggestions.
//
// **It emits a spec and builds nothing.** Everything below is said in the documents the studio already has —
// a grid of islands, a themes registry, dressing props, a room shell, an intent — and mapgen turns that into a
// world through the one export path. The sweep stays as code because a frozen file cannot notice that an
// eleventh house preset was added — so the spec is emitted fresh and never committed.
using System.Text.Json;
using System.Text.Json.Nodes;
using System.Text.Json.Serialization;
using PgmStudio.Domain;
using PgmStudio.MapGen;
using PgmStudio.Minecraft;
using PgmStudio.Minecraft.Dressing;
using PgmStudio.Pgm.Authoring;
using PgmStudio.Pgm.Sketch;

const int Columns = 5, Pitch = 56, Top = 26;
const int Surface = Top - 1;                       // the course a building stands on
const int Clay = Blocks.StainedClay, Wool = Blocks.Wool, Glass = Blocks.StainedGlass;

// Harness output rather than a checked-in seed: the emitter is the source and the spec is derived from
// it, so a committed copy would be a quarter of a megabyte of generated JSON going quietly stale the
// first time a house preset is added. Same arrangement as tools/tree-corpus/out — regenerated by
// re-running the tool, never reviewed as a diff.
var outPath = args.FirstOrDefault(a => !a.StartsWith("--")) ?? "tools/out/library-map.spec.json";

// ── what each plot shows ─────────────────────────────────────────────────────────────────────────────────

TerrainMaterial Shade(int block, int colour) => new SolidMaterial(block, colour);

// The area patterns, each used for both the ground and the riser, at the studio's own named seeds and scales.
TerrainMaterial Voronoi() => MaterialRecipes.Pattern("voronoi", "cobble");
TerrainMaterial Cells() => MaterialRecipes.Pattern("cell", "sand");
TerrainMaterial Noise() => MaterialRecipes.Pattern("noise", "verdant");
TerrainMaterial Turbulence() => MaterialRecipes.Pattern("turbulence", "rust");
TerrainMaterial Electric() => MaterialRecipes.Pattern("electric", "grey stone");

TerrainMaterial Frame(int angle) => new WallFrameMaterial(Shade(Clay, 15), Shade(Clay, 0), angle, Thickness: 1);

// A voronoi whose boundary band is one block — so it draws a clean grid of lines — and whose middle is handed
// to whatever is passed in. The grid stays legible because one material cannot vary.
TerrainMaterial RimAround(TerrainMaterial inside) =>
    new VoronoiMaterial(7, 13, [new VoronoiBand(Shade(Clay, 15), 1), new VoronoiBand(inside, 1)], Rise: 8);

// Greens broken into cells, for the five rings of the inward stack that read as a field rather than a course.
TerrainMaterial GrassVoronoi() =>
    new VoronoiMaterial(11, 7,
        [new VoronoiBand(new SolidMaterial(2, 0), 1), new VoronoiBand(Shade(Clay, 5), 1),
         new VoronoiBand(Shade(Clay, 13), 1)], Rise: 8);

// The author's own sequence as rings in from the outline: a rim, two rings of the next block, a checkered
// ring, five of a grass voronoi, and then nothing claimed — the surface takes over. HandOver is what makes the
// last part sayable: under Repeat the voronoi would run to the middle of the island.
TerrainMaterial Rings() =>
    new LayeredMaterial(
        new BandStack(
            [
                new Band(new SolidMaterial(4, 0), 1),                                  // ring 0 — a cobble rim
                new Band(new SolidMaterial(98, 0), 2),                                 // rings 1-2 — stone brick
                new Band(new CheckerMaterial(1, Shade(Clay, 15), Shade(Clay, 0)), 1),  // ring 3
                new Band(GrassVoronoi(), 5),                                           // rings 4-8
            ],
            BandEnding.HandOver),                                                      // ring 9 in — the surface
        BandAxis.Inward,
        Beyond: new SolidMaterial(2, 0));

// The pattern plots: what it shows, the outline it is drawn as, and the two materials that differ from the
// default finish. A null surface leaves the plot's top course plain grass, which is right wherever the wall is
// the thing being shown.
var patterns = new (string Name, string Kind, TerrainMaterial Wall, TerrainMaterial? Surface)[]
{
    // area patterns — on the ground and down the riser both
    ("voronoi — cobble family",                "rectangle", Voronoi(), Voronoi()),
    ("cell — sand family",                     "rectangle", Cells(), Cells()),
    ("noise — verdant family",                 "rectangle", Noise(), Noise()),
    ("turbulence — rust family",               "rectangle", Turbulence(), Turbulence()),
    ("electric — grey stone family",           "rectangle", Electric(), Electric()),

    // the plain kinds, and the board
    ("solid — grey stone",                     "rectangle", MaterialRecipes.One("grey stone"), null),
    ("layered — verdant/loam/stone",           "rectangle",
        new LayeredMaterial(new BandStack([
            new Band(MaterialRecipes.One("verdant"), 2), new Band(MaterialRecipes.One("loam"), 3),
            new Band(MaterialRecipes.One("grey stone"), 1)])), null),
    ("team tint — clay by team",               "rectangle",
        new TeamTintedMaterial(Clay, MaterialRecipes.One("ash")), null),
    ("checkerboard 1 — clay black/white",      "rectangle",
        new CheckerMaterial(1, Shade(Clay, 15), Shade(Clay, 0)),
        new CheckerMaterial(1, Shade(Clay, 15), Shade(Clay, 0))),
    ("checkerboard 3 — wool cyan/white",       "rectangle",
        new CheckerMaterial(3, Shade(Wool, 9), Shade(Wool, 0)),
        new CheckerMaterial(3, Shade(Wool, 9), Shade(Wool, 0))),

    // stripes along the wall, upright and sheared
    ("wall stripes — azure family",            "rectangle",
        new WallRunMaterial(MaterialRecipes.Stripes("azure", 3)), null),
    ("diagonal slope 1 — clay yellow/black",   "rectangle",
        new WallDiagonalMaterial([new WallStripe(Shade(Clay, 4), 2), new WallStripe(Shade(Clay, 15), 2)], 1), null),
    ("diagonal slope 2 — wool red/white",      "rectangle",
        new WallDiagonalMaterial([new WallStripe(Shade(Wool, 14), 3), new WallStripe(Shade(Wool, 0), 3)], 2), null),
    ("diagonal slope -1 — glass magenta/lime", "rectangle",
        new WallDiagonalMaterial([new WallStripe(Shade(Glass, 2), 2), new WallStripe(Shade(Glass, 5), 2)], -1), null),
    ("diagonal slope 3 — loam family",         "rectangle",
        new WallDiagonalMaterial(MaterialRecipes.Stripes("loam", 3, 4), 3), null),

    // the frame, and what decides a corner
    ("frame 45 — rectangle, 4 corners",        "rectangle", Frame(45), null),
    ("frame 45 — disc, no corner",             "circle",    Frame(45), null),
    ("frame 45 — octagon, at threshold",       "octagon",   Frame(45), null),
    ("frame 45 — cross, in and out",           "cross",     Frame(45), null),
    ("frame 80 — only the sharpest",           "wedge",     Frame(80), null),

    // patterns stacked inside patterns: every band, stop, stripe and square is itself a material
    ("voronoi rim, noise inside",              "rectangle", RimAround(Noise()), RimAround(Noise())),
    ("voronoi rim, cells inside",              "rectangle", RimAround(Cells()), RimAround(Cells())),
    ("frame ink, turbulence panel",            "rectangle",
        new WallFrameMaterial(Shade(Clay, 15), Turbulence(), 45, Thickness: 1), null),
    ("checker: plain against voronoi",         "rectangle",
        new CheckerMaterial(6, Shade(Clay, 0), Voronoi()), new CheckerMaterial(6, Shade(Clay, 0), Voronoi())),
    ("stripes, each a different kind",         "rectangle",
        new WallRunMaterial([new WallStripe(Shade(Clay, 15), 2), new WallStripe(Noise(), 6),
                             new WallStripe(Shade(Clay, 0), 2), new WallStripe(Turbulence(), 6)]), null),
};

// A theme whose top course is ringed and whose courses below it are not. The two axes compose rather than
// competing: the surface material is an ordinary depth stack whose first band is one course thick and is
// itself the inward stack, with dirt under it. The rim bucket is off, so the top course of an edge column
// falls to the surface (TP12) and the inward stack owns ring 0 itself — left on, the rim would paint that ring
// first and the stack's own first band would never be seen.
TerrainTheme RingTheme() => new()
{
    Rim = new TopBand(MaterialRecipes.One("ash", 2), 1, Enabled: false),
    Surface = new TopBand(
        new LayeredMaterial(new BandStack([new Band(Rings(), 1), new Band(new SolidMaterial(3, 0), 2)])),
        3, Enabled: true),
    Wall = MaterialRecipes.One("grey stone"),
    WallEnabled = true,
    Fill = MaterialRecipes.One("grey stone"),
};

// The ordinary finish: an inked rim, plain grass underfoot, and whatever the plot is showing on its wall.
TerrainTheme Finish(TerrainMaterial wall, TerrainMaterial? surface) => new()
{
    Rim = new TopBand(MaterialRecipes.One("ash", 2), 1, Enabled: true),
    Surface = new TopBand(surface ?? MaterialRecipes.Grass, 3, Enabled: true),
    Wall = wall,
    WallEnabled = true,
    Fill = MaterialRecipes.One("grey stone"),
};

// The whole sweep, in grid order: the patterns, then the inward axis on the two outlines its reading is
// easiest to see in, then one plot per house preset — plain underfoot, since on that row the plateau is not
// the thing being shown.
var plots = new List<(string Name, string Kind, TerrainTheme Theme)>();
plots.AddRange(patterns.Select(p => (Name: p.Name, Kind: p.Kind, Theme: Finish(p.Wall, p.Surface))));
plots.Add((Name: "inward rings — disc, rim to field", Kind: "circle", Theme: RingTheme()));
plots.Add((Name: "inward rings — cross, both corners", Kind: "cross", Theme: RingTheme()));
plots.AddRange(HousePresets.All.Select(house =>
    (Name: house.Name, Kind: "rectangle", Theme: Finish(MaterialRecipes.One("grey stone"), null))));

// ── the outlines, as offsets from a plot's own centre ────────────────────────────────────────────────────

// A regular octagon — every vertex turns 45°, which is exactly a wall frame's default threshold, so this is
// the plot that sits on the boundary of being cornered at all.
static double[][] Octagon(double radius)
{
    var cut = radius * 0.414;                       // the flat that makes eight equal sides
    return
    [
        [-cut, -radius], [cut, -radius], [radius, -cut], [radius, cut],
        [cut, radius], [-cut, radius], [-radius, cut], [-radius, -cut],
    ];
}

// A cross, as one twelve-vertex outline rather than two overlapping rectangles: four outward right angles and
// four inward ones, so a frame has to ink both kinds.
static double[][] Cross(double arm, double half) =>
[
    [-half, -arm], [half, -arm], [half, -half], [arm, -half], [arm, half], [half, half],
    [half, arm], [-half, arm], [-half, half], [-arm, half], [-arm, -half], [-half, -half],
];

static PlotSpec Outline(string kind, string name, string themeId) => kind switch
{
    "rectangle" => new PlotSpec { Kind = "rectangle", Name = name, Theme = themeId, Width = 34, Depth = 26 },
    "circle"    => new PlotSpec { Kind = "circle", Name = name, Theme = themeId, Radius = 14 },
    "octagon"   => new PlotSpec { Kind = "polygon", Name = name, Theme = themeId, Vertices = Octagon(15) },
    "cross"     => new PlotSpec { Kind = "polygon", Name = name, Theme = themeId, Vertices = Cross(15, 5) },
    "wedge"     => new PlotSpec
    {
        Kind = "polygon", Name = name, Theme = themeId,
        Vertices = [[-16, -15], [16, -15], [16, 15], [-9, 15]],
    },
    _ => throw new ArgumentException($"no plot outline '{kind}'"),
};

// ── the paint registry, and the plots that name into it ──────────────────────────────────────────────────

var themes = new JsonObject();
var plotSpecs = new List<PlotSpec>();
for (var index = 0; index < plots.Count; index++)
{
    var (name, kind, theme) = plots[index];
    var themeId = $"theme-{index}";
    themes[themeId] = JsonNode.Parse(TerrainThemeJson.Serialize(theme));
    plotSpecs.Add(Outline(kind, name, themeId));
}

var grid = new IslandGrid.Geometry(Columns, Pitch, Floor: 1, Top);
(int X, int Z) At(int index) => IslandGrid.Origin(index, plots.Count, grid);

// ── the dressing: a tree of every species and wood, and a house of every preset ──────────────────────────

// Half grown, half vanilla template, so the two forms stand side by side and the grown knobs vary plot to plot
// rather than repeating one tree a hundred times.
var props = new List<PlacedProp>();
var woods = new[] { "oak", "birch", "spruce", "jungle", "acacia", "dark oak" };
for (var index = 0; index < patterns.Length; index++)
{
    var (originX, originZ) = At(index);
    var spots = new[] { (-14, -10), (14, 10), (-13, 11), (15, -11) };
    for (var slot = 0; slot < spots.Length; slot++)
    {
        var (x, z) = (originX + spots[slot].Item1, originZ + spots[slot].Item2);
        props.Add(slot % 2 == 0
            ? new TreeProp
            {
                X = x, Z = z, Form = TreeForm.Grown, Wood = woods[(index + slot) % woods.Length],
                Height = 11 + (index + slot) % 9, Stems = 1 + (index + slot) % 3,
                Levels = 2 + (index / 5) % 2, Leader = 0.35 + 0.12 * ((index + slot) % 4),
                Flow = 0.25 + 0.15 * (slot % 4), BranchAngle = 0.35 + 0.15 * ((index + slot) % 5),
                LeafSize = 0.45 + 0.12 * (slot % 4),
            }
            : new TreeProp
            {
                X = x, Z = z,
                Species = DressingPalette.Species[(index + slot) % DressingPalette.Species.Count].Name,
                Height = 9 + (index + slot) % 6,
            });
    }
}

// One building per house preset, on the row of plots after the inward pair. They go down as dressing props
// rather than as rooms: a prop's footprint is a rectangle someone dragged and it carries no objective, which
// is exactly what a house standing on a plateau to be looked at is. The rectangle is stored as two opposite
// corners, the way the canvas stores a drag.
var houseRow = patterns.Length + 2;
for (var slot = 0; slot < HousePresets.All.Count; slot++)
{
    var house = HousePresets.All[slot];
    var (originX, originZ) = At(houseRow + slot);
    double minX = originX - house.Width / 2, minZ = originZ - house.Depth / 2;
    props.Add(new HouseProp
    {
        Wings = [new AuthoredWing([[minX, minZ], [minX + house.Width - 1, minZ + house.Depth - 1]])],
        Front = RoomEdge.NegZ,
        Style = house.Style,
    });
}

// The shell every wool room is stamped with, bound the way the studio's room-style step binds one. A gabled
// oak house rather than the shipped bedrock lid — which a stored style could not have asked for until the roof
// form became a column of its own. The spawns bind the third answer: no building. A spawn here is a pad and
// the monuments around it on open plateau, which is what a map wants wherever the ground itself is the room.
var oak = HouseStyle.Wool with
{
    Wall = RoomPart.Of(new SolidMaterial(5, 1), 5),        // spruce planks
    Roof = new RoofStyle
    {
        Form = RoofForm.Gable,
        Pitch = 1,
        Overhang = 1,
        Hole = false,
        Body = new SolidMaterial(5, 1),
        Verge = new SolidMaterial(5, 5),                   // dark oak, so the roof reads an edge
    },
    Post = new SolidMaterial(17, 0),                       // oak log at the corners: a house is framed
    Foundation = new Foundation
    {
        Plate = RoomPart.Of(new SolidMaterial(5, 0)),      // oak planks
        Footing = new SolidMaterial(4),                    // cobble
    },
    Doorway = new Doorway { Height = 3 },
};

// ── the intent: what the map is about ────────────────────────────────────────────────────────────────────

// A room and a spawn share no plot. Two structures on one 34×26 board leave them abutting along a single seam,
// which reads as one building split rather than two things with ground between them — and a spawn is meant to
// be somewhere a player crosses to the wool from. So each takes a plot of its own: the wool rooms keep the two
// plots they showed off, and the spawns take a plot on the far side of a stretch of void.
//
// Red's spawn is two rows south of its room rather than one, because the plot one row south is the wedge, and
// a 13×13 piece on a wedge would hang over the point of it. Every piece sits wholly on its plot: a piece that
// overhangs writes its foundation into the void, where StampFoundation finds no surface and lays one block at
// y=0 per overhanging cell instead of a column.
//
// A shell is its piece inset by one block on every side (WX1), so the piece's outer ring is bare plateau —
// which is the ring the bedrock floor fills and the entrance redstone runs along.
static Rect Centred((int X, int Z) origin, int width, int depth) =>
    new(origin.X - width / 2, origin.Z - depth / 2, origin.X - width / 2 + width, origin.Z - depth / 2 + depth);

var (westX, roomZ) = At(10);
var eastX = At(14).X;
var blueRoom = Centred((westX, roomZ), 15, 13);
var redRoom = Centred((eastX, roomZ), 15, 13);
var blueSpawnPiece = Centred(At(5), 13, 13);       // solid grey stone, north of the blue room
var redSpawnPiece = Centred(At(24), 13, 13);       // striped wall, south of the red room

// The door is the wall the yaw looks out of (0 = +z, 180 = −z). Each spawn faces the plot its wool room stands
// on: blue looks south across the void to its room, red looks north to its own.
const double FaceNegZ = 180, FacePosZ = 0;

// The entrance row EntranceRow picks: the first block row of the piece on the seam side, which is the bare
// ring outside the shell. Each room is entered from the side its team's spawn lies on.
static RedstoneLine RowOnMaxZ(Rect piece) =>
    new((int)piece.MinX, (int)piece.MaxZ - 1, (int)piece.MaxX - 1, (int)piece.MaxZ - 1);
static RedstoneLine RowOnMinZ(Rect piece) =>
    new((int)piece.MinX, (int)piece.MinZ, (int)piece.MaxX - 1, (int)piece.MinZ);

var intent = new MapIntent
{
    Teams =
    [
        new TeamDef { Id = "blue-team", Name = "Blue", Color = "blue" },
        new TeamDef { Id = "red-team", Name = "Red", Color = "red" },
    ],
    MaxPlayers = 8,
    Observer = new ObserverIntent { Point = new Pt(0, Surface + 60, roomZ) },
    Spawns =
    [
        new SpawnIntent
        {
            Team = "blue-team", Yaw = FacePosZ, Point = new Pt(westX, Surface + 1, At(5).Z),
            Piece = blueSpawnPiece, Protection = [blueSpawnPiece],
        },
        new SpawnIntent
        {
            Team = "red-team", Yaw = FaceNegZ, Point = new Pt(eastX, Surface + 1, At(24).Z),
            Piece = redSpawnPiece, Protection = [redSpawnPiece],
        },
    ],
    Wools =
    [
        new WoolIntent
        {
            Owner = "blue-team", Color = "red", Room = [blueRoom],
            Spawn = new Pt(westX, Surface + 1, roomZ), Piece = blueRoom,
            Entries = [new Rect(blueRoom.MinX, blueRoom.MinZ, blueRoom.MaxX, blueRoom.MinZ)],
        },
        new WoolIntent
        {
            Owner = "red-team", Color = "blue", Room = [redRoom],
            Spawn = new Pt(eastX, Surface + 1, roomZ), Piece = redRoom,
            Entries = [new Rect(redRoom.MinX, redRoom.MaxZ, redRoom.MaxX, redRoom.MaxZ)],
        },
    ],
    Structures = new StructureIntent
    {
        RoomFloors = [blueRoom, redRoom],
        RedstoneLines = [RowOnMinZ(blueRoom), RowOnMaxZ(redRoom)],
    },
};

// ── the spec ─────────────────────────────────────────────────────────────────────────────────────────────

// Only the fields that were stated: an overlay's explicit null means "no value" rather than "no change"
// (DocumentOverlay), so writing the unset half of a document would wipe what the grid produced.
var stated = new JsonSerializerOptions(JsonSerializerDefaults.Web)
{
    DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
    WriteIndented = true,
};

var layoutOverlay = new JsonObject
{
    ["themes"] = themes,
    ["mapTheme"] = "theme-0",
    ["roomStyles"] = new JsonObject
    {
        // The wire word for a bound wool shell is "cage" and not "wool" (SketchRoomStyles): a stored layout
        // spells it that way, and a key the reader does not know falls back to the built-in bedrock lid
        // without saying so — which is exactly what this emitter did until the merged layout was read back.
        ["cage"] = JsonNode.Parse(HouseStyleJson.Serialize(oak)),
        ["spawn"] = null,                       // open ground, which is a spawn's third answer
    },
    ["dressing"] = JsonNode.Parse(DressingJson.Serialize(new DressingDoc { Props = props })),
};

var spec = new MapSpec
{
    Slug = "library_map",
    Name = "Library Map",
    Objective = "Walk the plots: every terrain pattern, then the inward rings, then a house of every preset.",
    OutDir = "/media/sf_repos/CommunityMaps/ctw/library_map",
    Grid = new GridSpec { Columns = Columns, Pitch = Pitch, Floor = 1, Top = Top, Plots = plotSpecs },
    Layout = JsonSerializer.Deserialize<JsonElement>(layoutOverlay.ToJsonString()),
    Intent = JsonSerializer.Deserialize<JsonElement>(JsonSerializer.Serialize(intent, stated)),
};

Directory.CreateDirectory(Path.GetDirectoryName(Path.GetFullPath(outPath))!);
File.WriteAllText(outPath,
    "// Generated by tools/library-map.cs — do not hand-edit; re-run the emitter instead.\n"
  + "// mapgen skips comments, so this line is part of the spec rather than beside it.\n"
  + JsonSerializer.Serialize(spec, stated) + "\n");

Console.WriteLine($"wrote {outPath}");
Console.WriteLine($"  {plotSpecs.Count} plots · {themes.Count} themes · {props.OfType<TreeProp>().Count()} trees "
                + $"· {props.OfType<HouseProp>().Count()} buildings · {new FileInfo(outPath).Length / 1024} KB");
Console.WriteLine($"  build it: dotnet run --project tools/mapgen -- --stages {outPath}");
for (var index = 0; index < plotSpecs.Count; index++)
{
    var (x, z) = At(index);
    Console.WriteLine($"  x {x,5} z {z,5}   {plotSpecs[index].Name}");
}
