#:project ../../src/PgmStudio.Pgm/PgmStudio.Pgm.csproj
#:property JsonSerializerIsReflectionEnabledByDefault=true
// Generates the soft-term envelopes. Runs every SoftTerm's Value() over the authored seeds
// (tools/seeds/*.plan.json) — the same method the term scores with, so the band and the score can never drift
// — takes each metric's [min, max] across the seeds, and writes:
//   • src/PgmStudio.Pgm/Evaluate/seed-envelopes.json   (embedded, the bands the evaluator loads)
//   • docs/seed-envelopes.md                           (the human-readable band table + per-seed matrix)
// Checked in, never hand-edited: adding a teaching seed and re-running is how the evaluator learns the taste.
using System.Globalization;
using System.Text;
using System.Text.Json;
using PgmStudio.Pgm.Evaluate;
using PgmStudio.Pgm.Plan;

var seedDir = Path.Combine("tools", "seeds");
var files = Directory.EnumerateFiles(seedDir, "*.plan.json").OrderBy(p => p, StringComparer.Ordinal).ToList();
var seeds = files.Select(f => (Name: Path.GetFileName(f)[..^".plan.json".Length],
                               Ctx: EvalContext.Build(PlanModel.Parse(File.ReadAllText(f))!))).ToList();

var softTerms = LayoutEvaluator.AllTerms.OfType<SoftTerm>().ToList();

var bands = new Dictionary<string, double[]>();
var rows = new List<(string Id, string Rule, double Lo, double Hi, int N, List<(string Seed, double? V)> Values)>();
foreach (var term in softTerms)
{
    var values = seeds.Select(s => (s.Name, V: term.Value(s.Ctx))).ToList();
    var present = values.Where(v => v.V is not null).Select(v => v.V!.Value).ToList();
    if (present.Count == 0) { rows.Add((term.Id, term.RuleId, 0, 0, 0, values)); continue; }
    // floor the low, ceil the high (to 6 decimals): rounding must only ever WIDEN the band, never narrow it,
    // or a seed that defined a bound would fall just outside its own band.
    double lo = Math.Floor(present.Min() * 1e6) / 1e6, hi = Math.Ceiling(present.Max() * 1e6) / 1e6;
    bands[term.Id] = [lo, hi];
    rows.Add((term.Id, term.RuleId, lo, hi, present.Count, values));
}

var jsonPath = Path.Combine("src", "PgmStudio.Pgm", "Evaluate", "seed-envelopes.json");
File.WriteAllText(jsonPath, JsonSerializer.Serialize(bands, new JsonSerializerOptions { WriteIndented = true }) + "\n");
Console.WriteLine($"wrote {jsonPath} — {bands.Count} bands over {seeds.Count} seeds");

var md = new StringBuilder();
md.AppendLine("# Soft-term envelopes (generated — do not hand-edit)");
md.AppendLine();
md.AppendLine("Generated by `tools/deriver/envelope-stats.cs` from the authored seeds in `tools/seeds/`. Each");
md.AppendLine("band is `[min, max]` of the metric across the seeds that carry it; the evaluator scores a plan's");
md.AppendLine("distance outside the band (normalized by half-width). Re-run after adding a teaching seed.");
md.AppendLine();
md.AppendLine("## Bands");
md.AppendLine();
md.AppendLine("| term | rule | lo | hi | seeds |");
md.AppendLine("|---|---|---|---|---|");
foreach (var r in rows)
    md.AppendLine($"| `{r.Id}` | {r.Rule} | {Fmt(r.Lo)} | {Fmt(r.Hi)} | {r.N}/{seeds.Count} |");
md.AppendLine();
md.AppendLine("## Per-seed values");
md.AppendLine();
md.Append("| seed |");
foreach (var r in rows) md.Append($" {r.Id} |");
md.AppendLine();
md.Append("|---|");
foreach (var _ in rows) md.Append("---|");
md.AppendLine();
foreach (var s in seeds)
{
    md.Append($"| {s.Name} |");
    foreach (var r in rows)
    {
        var v = r.Values.First(x => x.Seed == s.Name).V;
        md.Append($" {(v is null ? "—" : Fmt(v.Value))} |");
    }
    md.AppendLine();
}
var mdPath = Path.Combine("docs", "seed-envelopes.md");
File.WriteAllText(mdPath, md.ToString());
Console.WriteLine($"wrote {mdPath}");

static string Fmt(double v) => (v == Math.Floor(v) ? ((long)v).ToString() : Math.Round(v, 3).ToString("0.###", CultureInfo.InvariantCulture));